config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }

  root to: "home#index"
  get :all_items, to: "home#all_items"
  get :stocks, to: "home#stocks"
  get :mines, to: "home#mines"
  post :md2html, to: "items#md2html"

  resources :items, only: %i(new edit create update destroy) do
    get :draft, on: :collection
    get :search, on: :collection
    resource :stock, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end

  resources :users, only: %i(show) do
    delete :twitter, on: :collection, to: "users#unlink_twitter"
    resources :items, only: %i(show)
    resource :following, only: %i(create destroy)
  end

  resources :tags, only: %i(show) do
    resource :following, only: %i(create destroy)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: %i(feeds items stocks mines)
end

app/helpers/home_helper.rb
module HomeHelper
  def active_in(path)
    "active" if current_page? path
  end

  def render_unless_empty(items)
    items.length > 0 ?
      render(items)
    : raw(message_when_empty)
  end

  def message_when_empty
    <<"no-items"
<p class="no-items">
  投稿はまだありません。
  <br>
  <a href="/items/new">Qiita全体の投稿</a>を見て、あなたの持っているtips、コードを投稿したり、タグやユーザーをフォローしてみましょう!
</p>
no-items
  end
end

app/views/home/_feed.html.haml
.feed
  :ruby
    arg = feed.class.name == "Item" ? feed : {
      partial: "items/item_box",
      locals: {
        item: item = (
          case feed.class.name
          when "Tagging" then feed.taggable
          when "Comment" then feed.commentable
          when "Stock" then feed.stockable
          end
        ),
        user: user = (
          case feed.class.name
          when "Tagging" then item.author
          when "Comment" then feed.commenter
          when "Stock" then feed.stocker
          end
        ),
        header: (
          case feed.class.name
          when "Tagging" then (link_to feed.tag.name, feed.tag) + "に新しい投稿がありました"
          when "Comment" then (link_to user.username, user) + "がコメントしました"
          when "Stock" then (link_to user.username, user) + "がストックしました"
          end
        )
      }
    }
  = render arg

app/views/home/_header.html.haml
.header
  %h2 プログラミング知識を共有しよう。
  = link_to "ノウハウ・Tipsを投稿する", new_item_path, class: "btn btn-primary"
%ul.nav.nav-tabs
  %li{class: active_in(root_path)}= link_to "フィード", root_path
  %li{class: active_in(all_items_path)}= link_to "すべての投稿", all_items_path
  %li.pull-right{class: active_in(mines_path)}= link_to "自分の投稿", mines_path
  %li.pull-right{class: active_in(stocks_path)}= link_to "ストック", stocks_path

app/views/home/_not_signed_in.html.haml
.col-md-7
  %span.logo
    Qiita Copy
  %h1.copy
    Qiita Copyは、プログラマのための
    %br
    技術情報共有サービスです。
.col-md-5
  .login.active
    = simple_form_for(:user, url: new_user_session_path) do |f|
      = f.input :email, placeholder: "メールアドレス", label: false
      .layout.horizontal.start
        .flex= f.input :password, placeholder: "パスワード", label: false
        = f.submit "ログイン", class: "btn btn-primary"
    .register
      .twitter
        = link_to "Twitterで新規登録/ログイン", omniauth_authorize_path(:user, :twitter), class: "btn btn-twitter btn-block"
      .mail
        または
        %a メールアドレスで登録
        する

  .signup
    = simple_form_for(:user, url: registration_path(:user)) do |f|
      = f.input :username, placeholder: "ユーザー名", label: false
      = f.input :email, placeholder: "メールアドレス", label: false
      = f.input :password, placeholder: "パスワード", label: false
      .layout.horizontal.end-justified.center
        %a キャンセル
        = f.submit "登録", class: "btn btn-primary"

app/views/home/all_items.html.haml
.container
  .row
    .col-md-12
      = render "header"
      = render_unless_empty Item.only_public.newer

app/views/home/index.html.haml
.container
  .row
    - if user_signed_in?
      .col-md-12
        = render "header"
        - current_user.feeds.each do |feed|
          = render partial: "home/feed", locals: {feed: feed}
        - if current_user.feeds.empty?
          = raw message_when_empty
    - else
      = render "not_signed_in"

app/views/home/items.html.haml
.container
  = render "header"
  = render_unless_empty @items.only_public.latest(10)

app/views/home/mines.html.haml
.container
  .row
    .col-md-12
      = render "header"
      = render_unless_empty current_user.items.only_public.newer

app/views/home/stocks.html.haml
.container
  .row
    .col-md-12
      = render 'header'
      = render_unless_empty current_user.stocked_items.newer