config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }

  root to: "home#index"
  get :all_items, to: "home#all_items"
  get :stocks, to: "home#stocks"
  get :mines, to: "home#mines"
  post :md2html, to: "items#md2html"

  resources :items, only: %i(new edit create update destroy) do
    get :draft, on: :collection
    get :search, on: :collection
    resource :stock, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end

  resources :users, only: %i(show) do
    delete :twitter, on: :collection, to: "users#unlink_twitter"
    resources :items, only: %i(show)
    resource :following, only: %i(create destroy)
  end

  resources :tags, only: %i(show) do
    resource :following, only: %i(create destroy)
  end
end

app/models/item.rb
class Item < ApplicationModel
  belongs_to :author, class_name: "User"
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :stocks, as: :stockable, dependent: :destroy
  has_many :stockers, through: :stocks
  has_many :comments, as: :commentable, dependent: :destroy

  scope :only_public, -> { where scope: :public }
  scope :only_private, -> { where scope: :private }
  scope :only_published, -> { where.not published_at: nil }
  scope :only_not_published, -> { where published_at: nil }
  scope :recent_stocked, -> { select("items.*, stocks.created_at").joins(:stocks).order('stocks.created_at desc').uniq }
  scope :search, -> q {
    q.split(" ")
      .map(&-> it { it.match(/((\S+):)?(\S+)/)}) # [ ["user:hoge", "user:", "user", "hoge"] ]
      .group_by(&-> it { it[2] })
      .to_a
      .reduce(self, &-> x, y {
        type, matches = y
        x.send "search_by_#{(type || "title").pluralize}", matches.map(&-> it { it[3] })
      })
  }
  scope :search_by_users, -> xs { joins(:author).where(User.arel_table[:username].eq_any xs) }
  scope :search_by_tags, -> xs { joins(:tags).where(Tag.arel_table[:name].eq_any xs) }
  scope :search_by_titles, -> xs { where(arel_table[:title].matches_any(xs.map &-> it { "%#{it}%" })) }

  after_initialize :set_default_value, if: :new_record?
  before_save :convert_crlf_to_lf_of_body, :set_published_at

  def tag_list
    tags.map(&:name).join " "
  end

  def tag_list=(tag_list)
    tags.replace(
      tag_list.split(/\s+/).map do |it|
        Tag.find_or_initialize_by name: it
      end
    )
  end

  def public?; scope == "public" end

  def private?; scope == "private" end

  private
    def convert_crlf_to_lf_of_body
      tap { |it| it.body.gsub! /\r\n/, "\n" }
    end

    def set_published_at
      self.published_at = Time.zone.now if scope_changed? && public?
    end

    def set_default_value
      self.scope ||= "public"
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include Md2html

  before_action :set_user, only: %i(show)
  before_action :set_item, only: %i(show edit update destroy)

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build item_params
    if @item.save
      redirect_to [current_user, @item], notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update item_params
      redirect_to [current_user, @item], notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to (request.referer == draft_items_path ? :back : mines_path), notice: "Item was successfully destroyed."
  end

  def md2html
    render json: {html: convert(params[:md])}
  end

  def search
    @items = Item.search(params[:q])
    @stocked_items = current_user.stocked_items.search(params[:q])
  end

  private
  def item_params
    params.require(:item).permit(:title, :body, :tag_list, :scope)
  end

  def set_user
    @user = User.find params[:user_id]
  end

  def set_item
    @item = (@user || current_user).items.find params[:id]
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= simple_form_for @item, :html => { :class => 'layout vertical' } do |f|
  = f.error_notification
  = f.input :title, placeholder: "タイトル", label: false
  = f.input :tag_list, placeholder: "タグをスペース区切りで入力（例: Ruby Rails:4.2.0）", label: false
  = f.input :scope, :as => :hidden, :input_html => { :value => @item.scope || "public"}
  .layout.horizontal.body.flex
    .flex.editor.layout.vertical
      %header 本文
      .flex= f.input :body, label: false
    .flex.preview.layout.vertical
      %header プレビュー
      .flex.content~ md(@item.body)
  .actions.layout.horizontal.end-justified
    .btn-group.dropup
      %button.btn.btn-primary{type: "submit"}
        %span{"data-scope": "private", class: ("selected" if @item.private?)}
          .glyphicon.glyphicon-save-file
          下書き保存
        %span{"data-scope": "public", class: ("selected" if @item.public?)}
          .glyphicon.glyphicon-cloud-upload
          投稿する
      %a.btn.btn-primary.dropdown-toggle{type: "button", "data-toggle": "dropdown"}
        .caret
      %ul.dropdown-menu.dropdown-menu-right
        %li{"data-scope": "private", class: ("selected" if @item.private?)}
          %a
            .glyphicon.glyphicon-save-file
            下書き保存
        %li{"data-scope": "public", class: ("selected" if @item.public?)}
          %a
            .glyphicon.glyphicon-cloud-upload
            投稿する

app/views/items/_item.html.haml
.item
  :ruby
    locals = {
      item: item,
      user: item.author,
      header: (
        (link_to item.author.username, item.author) +
        "が約#{time_ago_in_words item.published_at.try(:to_datetime)}前に投稿しました"
      )
    }
  = render partial: "items/item_box", locals: locals

app/views/items/_item_box.html.haml
.item-box
  = link_to user do
    = render partial: "users/icon", locals: {user: user}
  .content
    .header= header
    .title
      %h1= link_to item.title, [item.author, item]
      .tags= render item.tags
  .status
    = link_to item_stock_path(item), method: (current_user.stocks?(item) ? :delete : :post) do
      .glyphicon.glyphicon-folder-open{class: ("active" if current_user.stocks? item)}
    = item.stockers_count

app/views/items/_stock.html.haml
.stock-link
  - if current_user.stocks? item
    = link_to item_stock_path(item), method: :delete, class: "btn btn-primary", data: {toggle: "btn", "toggle-class": "btn-primary btn-danger"} do
      %span.active ストック済み
      %span 解除
  - else
    = link_to item_stock_path(item), method: :post, class: "btn btn-default" do
      .glyphicon.glyphicon-folder-open
      ストック

app/views/items/draft.html.haml
.container
  .row
    .col-md-3.sidebar
      .headline.layout.horizontal.justified.center
        %span 下書き一覧
        = link_to new_item_path, class: "btn btn-primary" do
          .glyphicon.glyphicon-pencil
      %ul.nav.nav-tabs
        %li.active{"data-toggle": "tab", "data-target": "#tab1"}= link_to "未投稿", "#"
        %li{"data-toggle": "tab", "data-target": "#tab2"}= link_to "投稿済み", "#"
      .tab-content
        .tab-pane.active#tab1
          - (items = current_user.items.only_private.only_not_published.newer).each do |item|
            = render partial: "items/draft/item", locals: {item: item, active: item == items.first}
        .tab-pane#tab2
          - (other_items = current_user.items.only_private.only_published.newer).each do |item|
            = render partial: "items/draft/item", locals: {item: item, active: false}
    .col-md-9
      - current_user.items.only_private.each do |item|
        .preview{class: ("active" if item == items.first), "data-id": item.id}
          .actions.layout.horizontal.justified.center
            = link_to edit_item_path(item), class: "btn btn-default" do
              .glyphicon.glyphicon-pencil
              編集
            = link_to item, method: :delete, class: "btn btn-link", data: {confirm: "Are you sure?"} do
              .glyphicon.glyphicon-trash
              削除
          .content
            %header
              %h1.title= item.title
              .tags
                = render item.tags
            .body~ md(item.body)

app/views/items/edit.html.haml
= render "form"

app/views/items/new.html.haml
= render "form"

app/views/items/search.html.haml
.container
  .row
    .col-md-8
      .search
        %form.layout.horizontal{action: search_items_path}
          %input.form-control.flex-6{type: "search", name: "q", placeholder: "キーワードを入力"}
          %button.btn.btn-primary.flex-1{type: "submit"}
            .glyphicon.glyphicon-search
              検索
      %ul.nav.nav-tabs
        %li.active{"data-toggle": "tab", "data-target": "#tab1"}= link_to "すべて", "#"
        %li{"data-toggle": "tab", "data-target": "#tab2"}= link_to "ストック済み", "#"
      .tab-content
        .tab-pane.active#tab1
          = render @items.newer
        .tab-pane#tab2
          = render @stocked_items.newer
    .col-md-4
      .help.panel.panel-default
        .panel-heading
          .glyphicon.glyphicon-search
          検索オプション
        .panel-body
          %dl
            %dt tag:Rails
            %dd 「Rails」タグが付いている
            %dt user:#{current_user.username}
            %dd #{current_user.username} が作成した

app/views/items/show.html.haml
.header
  .container
    .row
      .col-md-9
        %h2= @item.title
        .tags
          = render @item.tags
        .author
          = link_to @item.author do
            = render partial: "users/icon", locals: {user: @item.author}
          #{link_to @item.author.username, @item.author}が#{@item.published_at.to_date}に投稿
      .col-md-3
        .stats.layout.horizontal.center
          .flex.layout.vertical.center
            .num= @item.stockers_count
            .unit ストック
          .flex.layout.vertical.center
            .num= @item.comments_count
            .unit コメント
        .actions
          = render partial: "items/stock", locals: {item: @item}
          - if @item.author == current_user
            .own.layout.horizontal
              = link_to "編集", edit_item_path(@item), class: "flex btn btn-default"
              = link_to "削除", @item, method: :delete, data: {confirm: "Are you sure?"}, class: "flex btn btn-danger"
.container
  .row
    .col-md-12
      .body
        = md @item.body
      .comments-area
        - if @item.comments.length > 0
          .comments
            = render @item.comments
        - if user_signed_in?
          .new-comment
            .header
              = render partial: "users/icon", locals: {user: current_user}
              コメントを投稿する
            = render "comments/form"