config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }

  root to: "home#index"
  get :all_items, to: "home#all_items"
  get :stocks, to: "home#stocks"
  get :mines, to: "home#mines"
  post :md2html, to: "items#md2html"

  resources :items, only: %i(new edit create update destroy) do
    get :draft, on: :collection
    get :search, on: :collection
    resource :stock, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end

  resources :users, only: %i(show) do
    delete :twitter, on: :collection, to: "users#unlink_twitter"
    resources :items, only: %i(show)
    resource :following, only: %i(create destroy)
  end

  resources :tags, only: %i(show) do
    resource :following, only: %i(create destroy)
  end
end

app/views/layouts/_header.html.haml
%header
  .container
    .row.layout.horizontal.center
      %h1.logo
        = link_to "Qiita Copy", root_path
      .search.dropdown
        %form{action: search_items_path}
          %input.form-control{type: "search", name: "q", placeholder: "キーワードを入力"}
          .button.dropdown-toggle{type: "button", "data-toggle": "dropdown"}
            .caret
          .dropdown-menu
            %div
              %label ユーザーを指定
              %input.support.form-control{placeholder: "例) qiitan", "data-type": "user"}
            %div
              %label タグを指定
              %input.support.form-control{placeholder: "例) Ruby フレームワーク", "data-type": "tag"}
          %button.btn.btn-default{type: "submit"} 検索
      .flex.layout.horizontal.end-justified.center
        .btn-group.dropdown
          = link_to new_item_path, class: "btn btn-primary" do
            .glyphicon.glyphicon-edit
            %span 投稿する
          %a.btn.btn-primary.dropdown-toggle{type: "button", "data-toggle": "dropdown"}
            .caret
          %ul.dropdown-menu.dropdown-menu-right
            %li
              = link_to draft_items_path do
                .glyphicon.glyphicon-file
                下書き
        .user-menu.dropdown
          %a.dropdown-toggle{"data-toggle": "dropdown"}
            = render partial: "users/icon", locals: {user: current_user}
          %ul.dropdown-menu.dropdown-menu-right
            %li= link_to "マイページ", current_user
            %li= link_to "設定", edit_user_registration_path
            %li= link_to "ログアウト", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QiitaCopy
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{class: css_namespace}
    = render 'toastr_rails/flash'
    = render 'layouts/header' if user_signed_in?
    = yield